### ISSUE TITLE
Fix travis build

### ISSUE THREAD

**Issue by raphaelmeyer** [raphaelmeyer/caverna#18]
Update the project and fix the build on [travis ci](https://travis-ci.org/raphaelmeyer/caverna).

jdk version should be updated to 10, 11 or 12. openjdk is preferred.

**Comment by AlexeyPanchenko** [comment]
Why do you need exactly openjdk 10, 11 or 12 version?

**Comment by raphaelmeyer** [comment]
The jdk version itself is not that important.
The main focus is to get the build on travis working again, after gradle (#16) has been updated.
Maybe the jdk selection in [.travis.yml](https://github.com/raphaelmeyer/caverna/blob/master/.travis.yml) can be dropped completely.
The distribution may be set to bionic, if that helps.
